// apps/build-monitor/react/src/routes/BuildRequest.tsx
// TASK-099 (M4.5 Group E): BuildRequest (React) — POST /builds payload 직접 작성.
//
// Svelte src/routes/BuildRequest.svelte 와 1:1 정합. Svelte 측 admin pages 와
// 동일하게 cross-framework 공존 상태로 신규 추가 — App.tsx 의 /build-request
// 라우트가 React 측 page 로 교체. Svelte 측 route 는 그대로 유지되며
// TASK-101 Group G 에서 일괄 정리 예정.
//
// 동작 모드:
//   - login 직후 redirect 되어 진입. userId 는 localStorage 의 userId 키에서
//     직접 read (Svelte 측 session.ts 의 userIdStore 와 동등).
//   - userId 가 없으면 Login 페이지(`/login`) 로 redirect.
//   - payload 가 zod schema 와 일치해야 backend 가 202 (BuildAcceptedResponse)
//     또는 409 (BuildDuplicateResponse) 를 반환. invalid payload 는 zod 가
//     500 으로 reject → parseApiError 가 field-level banner 로 변환.
//
// 표준 검증 시나리오:
//   1) preset "Hello World" → "Submit Build" 클릭 → accepted toast + 결과 패널
//   2) 같은 appName 으로 즉시 재시도 → duplicate 배너 + 기존 build 표시
//   3) "Random appName" 클릭 → 다른 appName 으로 payload 갱신 후 submit

import { useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent, ReactElement } from "react";
import { Link, useNavigate } from "react-router-dom";

import { StatusPill } from "@/components/StatusPill";
import {
  parseApiError,
  submitBuildRequest,
  type BuildAcceptedResponse,
  type BuildDuplicateResponse,
  type BuildRequestPayload,
  type BuildRequestResponse
} from "@/lib/api";

import "./BuildRequest.css";

interface FieldError {
  path: string;
  message: string;
}

interface FormState {
  appName: string;
  requestedBy: string;
  objectKey: string;
  checksumSha256: string;
  sizeBytes: number;
  entrypointPath: string;
  dockerfilePath: string;
  previewTtlMinutes: number;
}

const DEFAULT_FORM: FormState = {
  appName: "",
  requestedBy: "",
  objectKey: "",
  checksumSha256: "",
  sizeBytes: 0,
  entrypointPath: "src/index.ts",
  dockerfilePath: "Dockerfile",
  previewTtlMinutes: 60
};

function makePreset(
  kind: "hello" | "minimal" | "typescript",
  userId: string | null
): FormState {
  const ts = Date.now().toString(36);
  const owner = userId ?? "alice";
  if (kind === "hello") {
    return {
      appName: `hello-${ts}`,
      requestedBy: owner,
      objectKey: "ref://github.com/example/hello-world",
      checksumSha256: "0".repeat(64),
      sizeBytes: 12345,
      entrypointPath: "src/index.ts",
      dockerfilePath: "Dockerfile",
      previewTtlMinutes: 60
    };
  }
  if (kind === "minimal") {
    return {
      appName: `minimal-${ts}`,
      requestedBy: owner,
      objectKey: "ref://github.com/example/minimal",
      checksumSha256: "0".repeat(64),
      sizeBytes: 4096,
      entrypointPath: "main.py",
      dockerfilePath: "Dockerfile",
      previewTtlMinutes: 15
    };
  }
  return {
    appName: `ts-app-${ts}`,
    requestedBy: owner,
    objectKey: "ref://github.com/example/ts-app",
    checksumSha256: "0".repeat(64),
    sizeBytes: 102400,
    entrypointPath: "src/server.ts",
    dockerfilePath: "Dockerfile",
    previewTtlMinutes: 60
  };
}

function randomizeAppName(): string {
  const ts = Date.now().toString(36);
  const rnd = Math.random().toString(36).slice(2, 6);
  return `random-${ts}-${rnd}`;
}

function isAccepted(r: BuildRequestResponse | null): r is BuildAcceptedResponse {
  return !!r && r.accepted === true && r.duplicate === false;
}

function isDuplicate(r: BuildRequestResponse | null): r is BuildDuplicateResponse {
  return !!r && r.accepted === false && r.duplicate === true;
}

export function BuildRequest(): ReactElement {
  const navigate = useNavigate();
  const [userId, setUserId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [form, setForm] = useState<FormState>(DEFAULT_FORM);
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [submitFieldErrors, setSubmitFieldErrors] = useState<FieldError[]>([]);
  const [lastResult, setLastResult] = useState<BuildRequestResponse | null>(null);

  // input ref — submit 시점에 React state batching 을 우회하여 native
  // input value 를 직접 read. controlled input 의 DOM property value 는
  // React 가 dispatch 후에 동기화되지만, onSubmit handler 가 호출되는
  // 시점에는 React state 가 batched 상태로 남아 있을 수 있어 production
  // 환경에서도 같은 race 가 발생할 수 있음. refs 는 항상 최신 DOM 값.
  const refs = {
    appName: useRef<HTMLInputElement>(null),
    requestedBy: useRef<HTMLInputElement>(null),
    objectKey: useRef<HTMLInputElement>(null),
    checksumSha256: useRef<HTMLInputElement>(null),
    sizeBytes: useRef<HTMLInputElement>(null),
    entrypointPath: useRef<HTMLInputElement>(null),
    dockerfilePath: useRef<HTMLInputElement>(null),
    previewTtlMinutes: useRef<HTMLInputElement>(null)
  };

  // userId store + 첫 진입 시 default preset 적용.
  useEffect(() => {
    const stored = localStorage.getItem("userId");
    if (!stored) {
      setLoading(false);
      navigate("/login", { replace: true });
      return;
    }
    setUserId(stored);
    setForm({ ...makePreset("hello", stored) });
    setLoading(false);
  }, [navigate]);

  // raw payload JSON preview. 마지막 form 변경마다 자동 갱신.
  const rawPayloadPreview = useMemo(() => {
    return JSON.stringify(
      {
        appName: form.appName,
        requestedBy: form.requestedBy,
        sourceArchive: {
          objectKey: form.objectKey,
          checksumSha256: form.checksumSha256,
          sizeBytes: form.sizeBytes
        },
        entrypointPath: form.entrypointPath,
        dockerfilePath: form.dockerfilePath,
        previewTtlMinutes: form.previewTtlMinutes
      },
      null,
      2
    );
  }, [form]);

  function applyPreset(kind: "hello" | "minimal" | "typescript"): void {
    setForm(makePreset(kind, userId));
  }

  function resetForm(): void {
    setLastResult(null);
    setSubmitError(null);
    setSubmitFieldErrors([]);
    setForm(makePreset("hello", userId));
  }

  async function submit(e: FormEvent<HTMLFormElement>): Promise<void> {
    e.preventDefault();
    setSubmitError(null);
    setSubmitFieldErrors([]);

    // React state batching 회피: input ref 로 native DOM value 직접 read.
    // fireEvent.change → setForm → setForm batch → submit 호출 사이의 race
    // 를 ref 기반 read 로 우회. refs 는 React render 와 무관하게 항상 최신
    // DOM property 를 가리키므로 controlled input 의 .value 가 React state
    // 와 sync 되지 않은 시점에서도 안정적.
    const readField = (ref: React.RefObject<HTMLInputElement>): string =>
      ref.current?.value ?? "";
    const appNameValue = readField(refs.appName);
    const requestedByValue = readField(refs.requestedBy);
    const objectKeyValue = readField(refs.objectKey);
    const checksumValue = readField(refs.checksumSha256);
    const sizeBytesValue = Number(readField(refs.sizeBytes));
    const entrypointValue = readField(refs.entrypointPath);
    const dockerfileValue = readField(refs.dockerfilePath);
    const previewTtlValue = Number(readField(refs.previewTtlMinutes));

    // form validation — zod 가 backend 에서도 검증하지만 client-side sanity
    // check 로 빠르게 피드백. BuildRequest schema 그대로. native form
    // element 의 현재 값을 사용 (React state batching 회피).
    const errs: FieldError[] = [];
    if (!appNameValue || appNameValue.length < 1) {
      errs.push({ path: "appName", message: "Required. Canonical app identity." });
    }
    if (!requestedByValue || requestedByValue.length < 1) {
      errs.push({ path: "requestedBy", message: "Required. Owner userId." });
    }
    if (!objectKeyValue || objectKeyValue.length < 1) {
      errs.push({
        path: "sourceArchive.objectKey",
        message: "Required. Skill 이 발행한 archive reference."
      });
    }
    if (!checksumValue || checksumValue.length < 1) {
      errs.push({
        path: "sourceArchive.checksumSha256",
        message: "Required. 64 hex chars expected."
      });
    }
    if (sizeBytesValue < 0 || !Number.isFinite(sizeBytesValue)) {
      errs.push({
        path: "sourceArchive.sizeBytes",
        message: "Non-negative integer."
      });
    }
    if (!entrypointValue || entrypointValue.length < 1) {
      errs.push({
        path: "entrypointPath",
        message: "Required. Container 시작점."
      });
    }
    if (!dockerfileValue || dockerfileValue.length < 1) {
      errs.push({
        path: "dockerfilePath",
        message: "Required. Default 'Dockerfile'."
      });
    }
    if (!Number.isInteger(previewTtlValue) || previewTtlValue <= 0) {
      errs.push({
        path: "previewTtlMinutes",
        message: "Positive integer. Default 60."
      });
    }
    if (errs.length > 0) {
      setSubmitFieldErrors(errs);
      return;
    }

    setSubmitting(true);
    try {
      const payload: BuildRequestPayload = {
        appName: appNameValue,
        requestedBy: requestedByValue,
        sourceArchive: {
          objectKey: objectKeyValue,
          checksumSha256: checksumValue,
          sizeBytes: Math.trunc(sizeBytesValue)
        },
        entrypointPath: entrypointValue,
        dockerfilePath: dockerfileValue,
        previewTtlMinutes: previewTtlValue,
        metadata: {}
      };
      const result = await submitBuildRequest(payload);
      setLastResult(result);
    } catch (err) {
      const parsed = parseApiError(err);
      if (parsed.fieldErrors.length > 0) {
        setSubmitFieldErrors(parsed.fieldErrors);
      } else {
        setSubmitError(parsed.summary);
      }
    } finally {
      setSubmitting(false);
    }
  }

  if (loading) {
    return <p className="muted">Loading…</p>;
  }

  return (
    <section className="page">
      <header className="page-head">
        <div>
          <h1>Build Request</h1>
          <p className="muted">
            Skill → Host 의 <code>POST /builds</code> payload 를 직접 작성하여
            제출합니다. 응답은 build server 의{" "}
            <code>BuildAcceptedResponse</code> (HTTP 202) 또는{" "}
            <code>BuildDuplicateResponse</code> (HTTP 409) 중 하나로 옵니다.
          </p>
        </div>
      </header>

      <div className="presets">
        <span className="label">Preset:</span>
        <button
          type="button"
          className="preset-btn"
          onClick={() => applyPreset("hello")}
          data-testid="req-preset-hello"
        >
          Hello World
        </button>
        <button
          type="button"
          className="preset-btn"
          onClick={() => applyPreset("minimal")}
          data-testid="req-preset-minimal"
        >
          Minimal (Python)
        </button>
        <button
          type="button"
          className="preset-btn"
          onClick={() => applyPreset("typescript")}
          data-testid="req-preset-typescript"
        >
          TypeScript
        </button>
        <button
          type="button"
          className="preset-btn secondary"
          onClick={() => setForm((prev) => ({ ...prev, appName: randomizeAppName() }))}
          data-testid="req-random"
        >
          ↻ Random appName
        </button>
      </div>

      <form className="form" onSubmit={submit} data-testid="req-form">
        <div className="grid">
          <label>
            <span className="lbl">appName <em>*</em></span>
            <input
              type="text"
              name="appName"
              ref={refs.appName}
              value={form.appName}
              onChange={(e) => setForm((prev) => ({ ...prev, appName: e.target.value }))}
              placeholder="hello-world"
              data-testid="req-appName"
            />
            <small className="hint">Canonical app identity. Active-build lock key.</small>
          </label>

          <label>
            <span className="lbl">requestedBy <em>*</em></span>
            <input
              type="text"
              name="requestedBy"
              ref={refs.requestedBy}
              value={form.requestedBy}
              onChange={(e) => setForm((prev) => ({ ...prev, requestedBy: e.target.value }))}
              placeholder="alice"
              data-testid="req-requestedBy"
            />
            <small className="hint">Owner userId. 같은 값으로 build list filter 가능.</small>
          </label>

          <label>
            <span className="lbl">sourceArchive.objectKey <em>*</em></span>
            <input
              type="text"
              name="objectKey"
              ref={refs.objectKey}
              value={form.objectKey}
              onChange={(e) => setForm((prev) => ({ ...prev, objectKey: e.target.value }))}
              placeholder="ref://github.com/owner/repo"
              data-testid="req-objectKey"
            />
            <small className="hint">Skill 이 발행한 archive reference.</small>
          </label>

          <label>
            <span className="lbl">sourceArchive.checksumSha256 <em>*</em></span>
            <input
              type="text"
              name="checksumSha256"
              ref={refs.checksumSha256}
              value={form.checksumSha256}
              onChange={(e) => setForm((prev) => ({ ...prev, checksumSha256: e.target.value }))}
              placeholder="0..0 (64 hex)"
              data-testid="req-checksum"
            />
            <small className="hint">실제 upload 시 server 가 검증. zod 는 min(1) 만 검사.</small>
          </label>

          <label>
            <span className="lbl">sourceArchive.sizeBytes <em>*</em></span>
            <input
              type="number"
              name="sizeBytes"
              ref={refs.sizeBytes}
              min={0}
              step={1}
              value={form.sizeBytes}
              onChange={(e) => {
                const next = e.target.value === "" ? 0 : Number(e.target.value);
                setForm((prev) => ({ ...prev, sizeBytes: Number.isFinite(next) ? next : 0 }));
              }}
              data-testid="req-sizeBytes"
            />
            <small className="hint">Archive byte size. non-negative.</small>
          </label>

          <label>
            <span className="lbl">entrypointPath <em>*</em></span>
            <input
              type="text"
              name="entrypointPath"
              ref={refs.entrypointPath}
              value={form.entrypointPath}
              onChange={(e) => setForm((prev) => ({ ...prev, entrypointPath: e.target.value }))}
              placeholder="src/index.ts"
              data-testid="req-entrypoint"
            />
            <small className="hint">Container 시작점.</small>
          </label>

          <label>
            <span className="lbl">dockerfilePath</span>
            <input
              type="text"
              name="dockerfilePath"
              ref={refs.dockerfilePath}
              value={form.dockerfilePath}
              onChange={(e) => setForm((prev) => ({ ...prev, dockerfilePath: e.target.value }))}
              placeholder="Dockerfile"
              data-testid="req-dockerfile"
            />
            <small className="hint">Default <code>Dockerfile</code>.</small>
          </label>

          <label>
            <span className="lbl">previewTtlMinutes</span>
            <input
              type="number"
              name="previewTtlMinutes"
              ref={refs.previewTtlMinutes}
              min={1}
              step={1}
              value={form.previewTtlMinutes}
              onChange={(e) => {
                const next = e.target.value === "" ? 0 : Number(e.target.value);
                setForm((prev) => ({
                  ...prev,
                  previewTtlMinutes: Number.isFinite(next) ? next : 0
                }));
              }}
              data-testid="req-ttl"
            />
            <small className="hint">Preview container TTL.</small>
          </label>
        </div>

        <div className="actions">
          <button
            type="submit"
            className="btn-primary"
            disabled={submitting}
            data-testid="req-submit"
          >
            {submitting ? "Submitting…" : "Submit Build"}
          </button>
          <button
            type="button"
            className="btn-secondary"
            onClick={resetForm}
            data-testid="req-reset"
          >
            Reset form
          </button>
          <Link to="/builds" className="btn-secondary" data-testid="req-list">
            View Builds list →
          </Link>
        </div>
      </form>

      {submitFieldErrors.length > 0 ? (
        <div className="banner error" role="alert" data-testid="req-field-errors">
          <strong>Form validation failed</strong>
          <ul className="field-errors">
            {submitFieldErrors.map((fe) => (
              <li key={fe.path}>
                <code className="field-path">{fe.path}</code>
                <span className="field-msg">{fe.message}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {submitError ? (
        <div className="banner error" role="alert" data-testid="req-error">
          <strong>Submit failed</strong>
          <pre>{submitError}</pre>
        </div>
      ) : null}

      {lastResult ? (
        <section className="result" data-testid="req-result">
          {isAccepted(lastResult) ? (
            <>
              <header className="result-head accepted">
                <span className="badge">202 Accepted</span>
                <h2>Build queued</h2>
              </header>
              <p>
                <code>appName={lastResult.build.appName}</code> 로 새 build 가
                QUEUED 상태로 등록됨. build server 가{" "}
                <code>REQUEST_ACCEPTED</code> phase 로 전이.
              </p>
              <dl className="kv">
                <dt>buildId</dt>
                <dd className="mono">{lastResult.build.buildId}</dd>
                <dt>status</dt>
                <dd>
                  <StatusPill
                    status={lastResult.build.status}
                    lifecycleStatus={lastResult.build.lifecycleStatus}
                  />
                </dd>
                <dt>phase</dt>
                <dd className="mono">{lastResult.build.phase}</dd>
                <dt>createdAt</dt>
                <dd className="mono">{lastResult.build.createdAt}</dd>
              </dl>
              <div className="actions">
                <Link
                  to={`/builds/${lastResult.build.buildId}`}
                  className="btn-primary"
                  data-testid="req-open-detail"
                >
                  Open Build Detail →
                </Link>
                <Link to="/builds" className="btn-secondary">
                  Back to list
                </Link>
              </div>
            </>
          ) : isDuplicate(lastResult) ? (
            <>
              <header className="result-head duplicate">
                <span className="badge">409 Duplicate</span>
                <h2>Active build already exists</h2>
              </header>
              <p>
                <code>appName={lastResult.build.appName}</code> 에 대해 active
                build 가 이미 존재. reason: <strong>{lastResult.reason}</strong>.
                기존 build 가 그대로 유지됨.
              </p>
              <dl className="kv">
                <dt>buildId</dt>
                <dd className="mono">{lastResult.build.buildId}</dd>
                <dt>status</dt>
                <dd>
                  <StatusPill
                    status={lastResult.build.status}
                    lifecycleStatus={lastResult.build.lifecycleStatus}
                  />
                </dd>
                <dt>phase</dt>
                <dd className="mono">{lastResult.build.phase}</dd>
              </dl>
              <div className="actions">
                <Link
                  to={`/builds/${lastResult.build.buildId}`}
                  className="btn-primary"
                  data-testid="req-open-existing"
                >
                  Open existing Build →
                </Link>
                <button
                  type="button"
                  className="btn-secondary"
                  onClick={() =>
                    setForm((prev) => ({ ...prev, appName: randomizeAppName() }))
                  }
                >
                  Try different appName
                </button>
              </div>
            </>
          ) : null}
        </section>
      ) : null}

      <details className="raw-payload">
        <summary>Raw payload preview (JSON)</summary>
        <pre>{rawPayloadPreview}</pre>
      </details>
    </section>
  );
}

// apps/build-monitor/src/routes/BuildRequest.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { push } from "svelte-spa-router";
  import { userIdStore } from "../lib/session.js";
  import {
    submitBuildRequest,
    type BuildRequestPayload,
    type BuildRequestResponse,
    type BuildAcceptedResponse,
    type BuildDuplicateResponse
  } from "../lib/api";

  // TASK-079 (skill 측 build request UI): 사용자가 build server 의
  // BuildRequest schema (skill → host) 를 직접 채워서 POST /builds 를 호출할
  // 수 있는 페이지. 사전 컴파일된 build-server (memory backend) 의 환경에서
  // 한두 번 클릭으로 build lifecycle 전체를 관찰할 수 있도록 한다.
  //
  // 동작 모드:
  //   - login 직후 redirect 되어 진입. userId 는 session.ts store 에서 가져옴.
  //   - userId 가 없으면 Login 페이지(`/`) 로 redirect.
  //   - payload 가 zod schema 와 일치해야 backend 가 202 (accepted) 또는 409
  //     (duplicate) 를 반환. invalid payload 는 zod 가 500 으로 reject.
  //
  // 표준 검증 시나리오 (시뮬레이션):
  //   1) preset "Hello World" → "Submit Build" 클릭 → accepted toast + 결과 패널
  //   2) 같은 appName 으로 즉시 재시도 → duplicate 배너 + 기존 build 표시
  //   3) "Random appName" 클릭 → 다른 appName 으로 payload 갱신 후 submit

  let userId = $derived($userIdStore);
  let loading = $state(true);

  // form fields. default 값은 preset 에서 일괄 교체.
  let appName = $state("");
  let requestedBy = $state("");
  let objectKey = $state("");
  let checksumSha256 = $state("");
  let sizeBytes = $state(0);
  let entrypointPath = $state("src/index.ts");
  let dockerfilePath = $state("Dockerfile");
  let previewTtlMinutes = $state(30);

  let submitting = $state(false);
  let submitError = $state<string | null>(null);

  // 가장 최근 응답을 화면에 표시. accepted/duplicate 둘 다.
  let lastResult = $state<BuildRequestResponse | null>(null);

  // preset 정의 — 한두 번 클릭으로 schema 검증 끝낼 수 있도록.
  // checksum 은 placeholder 형식 (64 hex chars). 실제 Skill 이 발행한 값은
  // 아니지만 backend 의 zod schema 가 min(1) 만 검사하므로 테스트 통과.
  function applyPreset(kind: "hello" | "minimal" | "typescript") {
    const ts = Date.now().toString(36);
    if (kind === "hello") {
      appName = `hello-${ts}`;
      requestedBy = userId ?? "alice";
      objectKey = `ref://github.com/example/hello-world`;
      checksumSha256 = "0".repeat(64);
      sizeBytes = 12345;
      entrypointPath = "src/index.ts";
      dockerfilePath = "Dockerfile";
      previewTtlMinutes = 30;
    } else if (kind === "minimal") {
      appName = `minimal-${ts}`;
      requestedBy = userId ?? "alice";
      objectKey = `ref://github.com/example/minimal`;
      checksumSha256 = "0".repeat(64);
      sizeBytes = 4096;
      entrypointPath = "main.py";
      dockerfilePath = "Dockerfile";
      previewTtlMinutes = 15;
    } else {
      appName = `ts-app-${ts}`;
      requestedBy = userId ?? "alice";
      objectKey = `ref://github.com/example/ts-app`;
      checksumSha256 = "0".repeat(64);
      sizeBytes = 102400;
      entrypointPath = "src/server.ts";
      dockerfilePath = "Dockerfile";
      previewTtlMinutes = 60;
    }
  }

  function randomizeAppName() {
    const ts = Date.now().toString(36);
    const rnd = Math.random().toString(36).slice(2, 6);
    appName = `random-${ts}-${rnd}`;
  }

  onMount(async () => {
    // userId 가 없으면 Login 페이지로 redirect (다른 인증 필요 route 와 동일).
    if (!userId) {
      loading = false;
      push("/");
      return;
    }
    // userId 로 default requestedBy 미리 채움.
    requestedBy = userId;
    // 첫 진입 시 default preset 으로 form 초기화.
    applyPreset("hello");
    loading = false;
  });

  async function submit() {
    submitError = null;
    lastResult = null;
    // form validation — zod 가 backend 에서도 검증하지만 client-side sanity
    // check 로 빠르게 피드백. BuildRequest schema 그대로.
    if (!appName || appName.length < 1) {
      submitError = "appName is required (BuildRequest schema)";
      return;
    }
    if (!requestedBy || requestedBy.length < 1) {
      submitError = "requestedBy is required";
      return;
    }
    if (!objectKey || objectKey.length < 1) {
      submitError = "sourceArchive.objectKey is required";
      return;
    }
    if (!checksumSha256 || checksumSha256.length < 1) {
      submitError = "sourceArchive.checksumSha256 is required";
      return;
    }
    if (sizeBytes < 0 || !Number.isFinite(sizeBytes)) {
      submitError = "sourceArchive.sizeBytes must be a non-negative integer";
      return;
    }
    if (!entrypointPath || entrypointPath.length < 1) {
      submitError = "entrypointPath is required";
      return;
    }

    submitting = true;
    try {
      // BuildRequest schema 의 `metadata` 필드는 zod default({}) 가 있어
      // backend 에서 optional 이지만, .generated/openapi.d.ts 의 components
      // alias 가 required 로 잡힘 (openapi-typescript 의 default 추론
      // 한계). 빈 객체로 명시 — payload 가 너무 단순하면 type-cast 로
      // 우회하지만 metadata 도 함께 보내는 편이 schema 와 더 잘 맞음.
      const payload: BuildRequestPayload = {
        appName,
        requestedBy,
        sourceArchive: { objectKey, checksumSha256, sizeBytes: Math.trunc(sizeBytes) },
        entrypointPath,
        dockerfilePath,
        previewTtlMinutes,
        metadata: {}
      };
      lastResult = await submitBuildRequest(payload);
    } catch (e) {
      submitError = e instanceof Error ? e.message : String(e);
    } finally {
      submitting = false;
    }
  }

  // 빌드 detail 페이지로 이동 — accepted result 의 buildId 사용.
  function openBuildDetail(buildId: string) {
    push(`/builds/${buildId}`);
  }

  // 결과 분류 helper.
  function isAccepted(r: BuildRequestResponse | null): r is BuildAcceptedResponse {
    return !!r && r.accepted === true && r.duplicate === false;
  }
  function isDuplicate(r: BuildRequestResponse | null): r is BuildDuplicateResponse {
    return !!r && r.accepted === false && r.duplicate === true;
  }
</script>

<section class="page">
  <header class="page-head">
    <div>
      <h1>Build Request</h1>
      <p class="muted">
        Skill → Host 의 <code>POST /builds</code> payload 를 직접 작성하여 제출합니다.
        응답은 build server 의 <code>BuildAcceptedResponse</code> (HTTP 202) 또는
        <code>BuildDuplicateResponse</code> (HTTP 409) 중 하나로 옵니다.
      </p>
    </div>
  </header>

  {#if loading}
    <p class="muted">Loading…</p>
  {:else}
    <div class="presets">
      <span class="label">Preset:</span>
      <button type="button" class="preset-btn" onclick={() => applyPreset("hello")}>
        Hello World
      </button>
      <button type="button" class="preset-btn" onclick={() => applyPreset("minimal")}>
        Minimal (Python)
      </button>
      <button type="button" class="preset-btn" onclick={() => applyPreset("typescript")}>
        TypeScript
      </button>
      <button type="button" class="preset-btn secondary" onclick={randomizeAppName}>
        ↻ Random appName
      </button>
    </div>

    <form class="form" onsubmit={(e) => { e.preventDefault(); submit(); }}>
      <div class="grid">
        <label>
          <span class="lbl">appName <em>*</em></span>
          <input type="text" bind:value={appName} placeholder="hello-world" data-testid="req-appName" />
          <small class="hint">Canonical app identity. Active-build lock key.</small>
        </label>

        <label>
          <span class="lbl">requestedBy <em>*</em></span>
          <input type="text" bind:value={requestedBy} placeholder="alice" data-testid="req-requestedBy" />
          <small class="hint">Owner userId. 같은 값으로 build list filter 가능.</small>
        </label>

        <label>
          <span class="lbl">sourceArchive.objectKey <em>*</em></span>
          <input type="text" bind:value={objectKey} placeholder="ref://github.com/owner/repo" data-testid="req-objectKey" />
          <small class="hint">Skill 이 발행한 archive reference.</small>
        </label>

        <label>
          <span class="lbl">sourceArchive.checksumSha256 <em>*</em></span>
          <input type="text" bind:value={checksumSha256} placeholder="0..0 (64 hex)" data-testid="req-checksum" />
          <small class="hint">실제 upload 시 server 가 검증. zod 는 min(1) 만 검사.</small>
        </label>

        <label>
          <span class="lbl">sourceArchive.sizeBytes <em>*</em></span>
          <input
            type="number"
            min="0"
            step="1"
            bind:value={sizeBytes}
            data-testid="req-sizeBytes"
          />
          <small class="hint">Archive byte size. non-negative.</small>
        </label>

        <label>
          <span class="lbl">entrypointPath <em>*</em></span>
          <input type="text" bind:value={entrypointPath} placeholder="src/index.ts" data-testid="req-entrypoint" />
          <small class="hint">Container 시작점.</small>
        </label>

        <label>
          <span class="lbl">dockerfilePath</span>
          <input type="text" bind:value={dockerfilePath} placeholder="Dockerfile" data-testid="req-dockerfile" />
          <small class="hint">Default <code>Dockerfile</code>.</small>
        </label>

        <label>
          <span class="lbl">previewTtlMinutes</span>
          <input type="number" min="1" step="1" bind:value={previewTtlMinutes} data-testid="req-ttl" />
          <small class="hint">Preview container TTL.</small>
        </label>
      </div>

      <div class="actions">
        <button type="submit" class="btn-primary" disabled={submitting} data-testid="req-submit">
          {submitting ? "Submitting…" : "Submit Build"}
        </button>
        <button type="button" class="btn-secondary" onclick={() => push("/builds")} data-testid="req-cancel">
          View Builds list
        </button>
      </div>
    </form>

    {#if submitError}
      <div class="banner error" role="alert" data-testid="req-error">
        <strong>Submit failed</strong>
        <pre>{submitError}</pre>
      </div>
    {/if}

    {#if lastResult}
      <section class="result" data-testid="req-result">
        {#if isAccepted(lastResult)}
          <header class="result-head accepted">
            <span class="badge">202 Accepted</span>
            <h2>Build queued</h2>
          </header>
          <p>
            <code>appName={lastResult.build.appName}</code> 로 새 build 가 QUEUED 상태로 등록됨.
            build server 가 <code>REQUEST_ACCEPTED</code> phase 로 전이.
          </p>
          <dl class="kv">
            <dt>buildId</dt>
            <dd class="mono">{lastResult.build.buildId}</dd>
            <dt>status</dt>
            <dd><span class="chip status-{lastResult.build.status.toLowerCase()}">{lastResult.build.status}</span></dd>
            <dt>phase</dt>
            <dd class="mono">{lastResult.build.phase}</dd>
            <dt>createdAt</dt>
            <dd class="mono">{lastResult.build.createdAt}</dd>
          </dl>
          <div class="actions">
            <button type="button" class="btn-primary" onclick={() => openBuildDetail(lastResult!.build.buildId)} data-testid="req-open-detail">
              Open Build Detail →
            </button>
            <button type="button" class="btn-secondary" onclick={() => push("/builds")}>
              Back to list
            </button>
          </div>
        {:else if isDuplicate(lastResult)}
          <header class="result-head duplicate">
            <span class="badge">409 Duplicate</span>
            <h2>Active build already exists</h2>
          </header>
          <p>
            <code>appName={lastResult.build.appName}</code> 에 대해 active build 가 이미 존재.
            reason: <strong>{lastResult.reason}</strong>. 기존 build 가 그대로 유지됨.
          </p>
          <dl class="kv">
            <dt>buildId</dt>
            <dd class="mono">{lastResult.build.buildId}</dd>
            <dt>status</dt>
            <dd><span class="chip status-{lastResult.build.status.toLowerCase()}">{lastResult.build.status}</span></dd>
            <dt>phase</dt>
            <dd class="mono">{lastResult.build.phase}</dd>
          </dl>
          <div class="actions">
            <button type="button" class="btn-primary" onclick={() => openBuildDetail(lastResult!.build.buildId)} data-testid="req-open-existing">
              Open existing Build →
            </button>
            <button type="button" class="btn-secondary" onclick={randomizeAppName}>
              Try different appName
            </button>
          </div>
        {/if}
      </section>
    {/if}

    <details class="raw-payload">
      <summary>Raw payload preview (JSON)</summary>
      <pre>{JSON.stringify({
        appName,
        requestedBy,
        sourceArchive: { objectKey, checksumSha256, sizeBytes },
        entrypointPath,
        dockerfilePath,
        previewTtlMinutes
      }, null, 2)}</pre>
    </details>
  {/if}
</section>

<style>
  .page {
    display: flex;
    flex-direction: column;
    gap: var(--space-lg);
    animation: fadeIn var(--motion-duration-slow) var(--motion-easing-standard);
    max-width: 960px;
  }
  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
  }
  .page-head h1 {
    margin: 0;
    font-size: var(--size-xxl);
    font-weight: var(--weight-semibold);
    letter-spacing: -0.02em;
    background: linear-gradient(90deg, var(--color-text-primary), var(--color-text-muted));
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
  }
  .page-head .muted {
    color: var(--color-text-muted);
    margin-top: var(--space-xs);
    line-height: var(--motion-duration-base);
  }
  .muted { color: var(--color-text-muted); }

  .presets {
    display: flex;
    align-items: center;
    gap: var(--space-sm);
    flex-wrap: wrap;
    padding: var(--space-md);
    background: var(--color-bg-surface);
    border-radius: var(--radius-md);
    border: 1px solid var(--color-border-subtle);
  }
  .presets .label {
    font-size: var(--size-xs);
    font-weight: var(--weight-semibold);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-secondary);
  }
  .preset-btn {
    padding: var(--space-xs) var(--space-md);
    border-radius: var(--radius-md);
    background: var(--color-bg-surface-elevated);
    color: var(--color-text-primary);
    font-size: var(--size-sm);
    font-weight: var(--weight-medium);
    border: 1px solid var(--color-border-subtle);
    cursor: pointer;
    transition: all var(--motion-duration-fast) var(--motion-easing-standard);
  }
  .preset-btn:hover {
    background: var(--color-accent-primary);
    color: white;
    border-color: var(--color-accent-primary);
  }
  .preset-btn.secondary {
    background: transparent;
    color: var(--color-text-secondary);
  }

  .form {
    background: var(--color-bg-surface);
    padding: var(--space-lg);
    border-radius: var(--radius-lg);
    border: 1px solid var(--color-border-subtle);
    box-shadow: var(--shadow-card);
  }
  .grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: var(--space-lg);
    margin-bottom: var(--space-lg);
  }
  @media (max-width: 640px) {
    .grid { grid-template-columns: 1fr; }
  }
  label {
    display: flex;
    flex-direction: column;
    gap: var(--space-xs);
  }
  label .lbl {
    font-size: var(--size-xs);
    font-weight: var(--weight-semibold);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-secondary);
  }
  label .lbl em {
    color: var(--color-accent-danger);
    font-style: normal;
    margin-left: 2px;
  }
  input[type="text"], input[type="number"] {
    padding: var(--space-sm) var(--space-md);
    border-radius: var(--radius-md);
    border: 1px solid var(--color-border-default);
    background: var(--color-bg-surface-elevated);
    color: var(--color-text-primary);
    font-family: var(--font-mono, monospace);
    font-size: var(--size-sm);
    transition: border-color var(--motion-duration-fast) var(--motion-easing-standard);
  }
  input:focus {
    outline: none;
    border-color: var(--color-accent-primary);
    box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.2);
  }
  .hint {
    color: var(--color-text-muted);
    font-size: var(--size-xs);
  }
  .hint code {
    background: var(--color-bg-surface-elevated);
    padding: 0 4px;
    border-radius: var(--radius-sm);
    font-family: var(--font-mono, monospace);
  }

  .actions {
    display: flex;
    gap: var(--space-sm);
    flex-wrap: wrap;
    align-items: center;
  }
  .btn-primary {
    padding: var(--space-sm) var(--space-xl);
    border-radius: var(--radius-md);
    background: var(--color-accent-primary);
    color: white;
    font-weight: var(--weight-semibold);
    font-size: var(--size-sm);
    border: none;
    cursor: pointer;
    transition: all var(--motion-duration-fast) var(--motion-easing-standard);
    box-shadow: 0 4px 12px rgba(99, 102, 241, 0.4);
  }
  .btn-primary:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 6px 16px rgba(99, 102, 241, 0.5);
  }
  .btn-primary:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
  .btn-secondary {
    padding: var(--space-sm) var(--space-xl);
    border-radius: var(--radius-md);
    background: transparent;
    color: var(--color-text-secondary);
    font-weight: var(--weight-medium);
    font-size: var(--size-sm);
    border: 1px solid var(--color-border-subtle);
    cursor: pointer;
    transition: all var(--motion-duration-fast) var(--motion-easing-standard);
  }
  .btn-secondary:hover {
    color: var(--color-text-primary);
    border-color: var(--color-text-secondary);
  }

  .banner {
    padding: var(--space-md) var(--space-lg);
    border-radius: var(--radius-md);
    border: 1px solid var(--color-border-subtle);
    background: var(--color-bg-surface);
  }
  .banner.error {
    border-color: var(--color-accent-danger);
    background: rgba(244, 63, 94, 0.08);
  }
  .banner pre {
    margin: var(--space-sm) 0 0;
    white-space: pre-wrap;
    word-break: break-word;
    color: var(--color-text-primary);
    font-family: var(--font-mono, monospace);
    font-size: var(--size-sm);
  }

  .result {
    background: var(--color-bg-surface);
    padding: var(--space-lg);
    border-radius: var(--radius-lg);
    border: 1px solid var(--color-border-subtle);
    box-shadow: var(--shadow-card);
  }
  .result-head {
    display: flex;
    align-items: center;
    gap: var(--space-md);
    margin-bottom: var(--space-md);
  }
  .result-head h2 {
    margin: 0;
    font-size: var(--size-lg);
    font-weight: var(--weight-semibold);
  }
  .result-head.accepted { color: var(--color-accent-success, #22c55e); }
  .result-head.duplicate { color: var(--color-accent-warning, #f59e0b); }
  .badge {
    display: inline-block;
    padding: var(--space-xs) var(--space-md);
    border-radius: var(--radius-pill);
    font-family: var(--font-mono, monospace);
    font-size: var(--size-xs);
    font-weight: var(--weight-semibold);
    color: white;
  }
  .result-head.accepted .badge { background: var(--color-accent-success, #22c55e); }
  .result-head.duplicate .badge { background: var(--color-accent-warning, #f59e0b); }

  .kv {
    display: grid;
    grid-template-columns: 140px 1fr;
    gap: var(--space-sm) var(--space-md);
    margin: var(--space-md) 0;
    padding: var(--space-md);
    background: var(--color-bg-surface-elevated);
    border-radius: var(--radius-md);
    border: 1px solid var(--color-border-subtle);
  }
  .kv dt {
    font-size: var(--size-xs);
    font-weight: var(--weight-semibold);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--color-text-muted);
    align-self: center;
  }
  .kv dd {
    margin: 0;
    color: var(--color-text-primary);
    font-family: var(--font-mono, monospace);
    font-size: var(--size-sm);
    word-break: break-all;
  }
  .kv dd.mono { font-family: var(--font-mono, monospace); }
  .chip {
    display: inline-block;
    padding: 2px var(--space-sm);
    border-radius: var(--radius-pill);
    font-family: var(--font-mono, monospace);
    font-size: var(--size-xs);
    font-weight: var(--weight-semibold);
    color: white;
  }
  .chip.status-queued { background: var(--color-text-muted); }
  .chip.status-building { background: var(--color-accent-info, #3b82f6); }
  .chip.status-completed { background: var(--color-accent-success, #22c55e); }
  .chip.status-failed { background: var(--color-accent-danger, #ef4444); }

  .raw-payload {
    margin-top: var(--space-md);
    background: var(--color-bg-surface);
    border: 1px solid var(--color-border-subtle);
    border-radius: var(--radius-md);
    padding: var(--space-md);
  }
  .raw-payload summary {
    cursor: pointer;
    font-size: var(--size-sm);
    font-weight: var(--weight-medium);
    color: var(--color-text-secondary);
  }
  .raw-payload pre {
    margin-top: var(--space-md);
    padding: var(--space-md);
    background: var(--color-bg-surface-elevated);
    border-radius: var(--radius-sm);
    font-family: var(--font-mono, monospace);
    font-size: var(--size-xs);
    color: var(--color-text-primary);
    overflow-x: auto;
  }
</style>
