// apps/build-monitor/src/components/Header.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { link, push } from "svelte-spa-router";
  import ThemeToggle from "./ThemeToggle.svelte";
  import { userIdStore } from "../lib/session.js";
  import { adminAllowListStore } from "../lib/admin-store.js";

  // session.ts 의 writable store 가 localStorage 와 양방향 동기화를
  // 담당한다 (Bug 1: 로그인 직후 Header 가 즉시 갱신되도록). 컴포넌트
  // state 를 따로 두지 않고 store 값을 직접 구독한다.
  //
  // TASK-076: 별도 adminId store 는 제거됐다. admin 권한은 userId 가
  // admin allow-list 에 속해 있으면 자동 부여되며, userId 만으로 admin
  // session 을 암묵적으로 잡는다 (별도 admin login / logout 단계 없음).
  let userId = $derived($userIdStore);

  // TASK-048: admin allow-list 캐시. userId 가 admin list 에 포함되어
  // 있으면 admin 메뉴를 자동으로 노출한다 (별도 AdminLogin 단계 없이).
  // 빈 배열은 "아직 fetch 안 됨" 또는 "fetch 실패" 상태이며, 이 경우
  // auto-enable 도 false 로 두어 비-admin 사용자가 admin 메뉴를 보지
  // 못하도록 한다.
  let adminAllowList = $derived($adminAllowListStore);

  // userId 가 adminAllowList 에 포함되면 admin 으로 auto-enable. 단,
  // userId 가 없거나 allowList 가 비어있으면 false.
  let autoAdminEnabled = $derived(
    !!userId && adminAllowList.length > 0 && adminAllowList.includes(userId)
  );

  // 표시할 admin id = userId 그 자체 (TASK-076). 별도 admin session 이
  // 없으므로 logout 하면 userIdStore 가 null 이 되는 순간 admin 메뉴도
  // 자연스럽게 사라진다.
  let effectiveAdminId = $derived(autoAdminEnabled ? userId : null);

  function logout() {
    // userId 가 admin allow-list 에 있었더라도, logout 하면 더 이상
    // admin 메뉴는 노출되지 않는다 — userId null 이 되면
    // autoAdminEnabled 도 false 가 되므로 admin 메뉴가 자연스럽게 사라진다.
    userIdStore.set(null);
    push("/");
  }

  // 부팅 시 userId 가 있으면 admin allow-list 를 prefetch 한다. userId 가
  // admin list 에 속해 있으면 즉시 admin 메뉴가 노출되고, 아니면 admin
  // 메뉴는 표시되지 않는다. 실패 시 (offline / 비-401 응답) 캐시는 빈
  // 배열로 남고 admin 메뉴는 비활성화된다 — 이전에는 이때 `/admin/login`
  // 으로 fallback 했지만 TASK-076 에서는 그 entry 가 사라졌으므로
  // 단순히 admin 메뉴만 닫힌다.
  onMount(async () => {
    if (userId && adminAllowList.length === 0) {
      try {
        await adminAllowListStore.refresh(userId);
      } catch {
        // intentional: stale cache; admin menu stays hidden until next
        // successful refresh (e.g. next page navigation trigger).
      }
    }
  });
</script>

<header class="hdr">
  <div class="hdr-inner">
    <a use:link href="/" class="brand">
      <div class="logo-wrapper">
        <span class="logo" aria-hidden="true">⬢</span>
      </div>
      <span class="title">Build Monitor</span>
    </a>
    <nav>
      {#if userId}
        <span class="user-id mono">@{userId}</span>
        <a use:link href="/builds">Builds</a>
        <!-- TASK-079 (skill 측 build request UI): 일반 인증 사용자 (admin
             여부 무관) 가 POST /builds payload 를 직접 작성해 lifecycle
             을 시험할 수 있는 진입점. Header 의 첫 nav 로 노출하여
             로그인 직후 가장 빠르게 접근 가능하도록 함. -->
        <a use:link href="/build-request">New Build</a>
        <button class="logout-btn" onclick={logout}>Logout</button>
      {/if}
      {#if effectiveAdminId}
        <div class="divider"></div>
        <span class="admin-id mono" title="Admin session active">🛡 @{effectiveAdminId}</span>
        <!-- TASK-077: admin 진입점은 단일 링크. 각 admin 섹션 (Builds /
             Users / Admins / Runners) 사이의 이동은 페이지 상단
             <AdminTabs /> 가 담당한다. -->
        <a use:link href="/admin/builds">Admin</a>
      {/if}
      <div class="divider"></div>
      <!-- API Console: SPA 안에서 Swagger UI 를 임베드한 페이지.
           build 요청을 시험하면서 동시에 OpenAPI contract 를 확인할 수 있게
           함. 외부 `/docs/` 로 새 탭 열기보다 SPA 흐름 유지가 자연스러움. -->
      <a use:link href="/api-console" data-testid="hdr-api-console">API Console</a>
      <!-- OpenAPI: raw JSON spec — 다운로드 / 외부 검증 도구 입력용. -->
      <a href="/openapi.json" target="_blank" rel="noopener" data-testid="hdr-openapi">OpenAPI</a>
      <!-- Docs: build-server Swagger UI 를 외부 새 탭에서 열기. -->
      <a href="/docs/" target="_blank" rel="noopener" data-testid="hdr-docs">Docs</a>
      <div class="divider"></div>
      <ThemeToggle />
    </nav>
  </div>
</header>

<style>
  .hdr {
    position: sticky;
    top: 0;
    z-index: var(--z-header);
    background: var(--glass-bg);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    border-bottom: 1px solid var(--glass-border);
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
    transition: background-color var(--motion-duration-base) var(--motion-easing-standard);
  }
  .hdr-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 var(--space-xl);
    height: 64px;
    max-width: 1440px;
    margin: 0 auto;
  }
  .brand {
    display: inline-flex;
    align-items: center;
    gap: var(--space-sm);
    color: var(--color-text-primary);
    font-weight: var(--weight-semibold);
    font-size: var(--size-lg);
    letter-spacing: -0.01em;
  }
  .brand:hover { text-decoration: none; }
  .logo-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: var(--radius-md);
    background: linear-gradient(135deg, var(--color-accent-primary), var(--color-accent-info));
    box-shadow: var(--shadow-glow);
  }
  .logo {
    color: white;
    font-size: var(--size-lg);
    line-height: 1;
  }
  nav {
    display: flex;
    align-items: center;
    gap: var(--space-lg);
  }
  nav a {
    color: var(--color-text-secondary);
    font-weight: var(--weight-medium);
    font-size: var(--size-sm);
    transition: color var(--motion-duration-fast) var(--motion-easing-standard);
  }
  nav a:hover {
    color: var(--color-text-primary);
    text-decoration: none;
  }
  .user-id {
    color: var(--color-text-primary);
    font-size: var(--size-sm);
    font-weight: var(--weight-semibold);
    background: var(--color-bg-surface-elevated);
    padding: var(--space-xs) var(--space-md);
    border-radius: var(--radius-pill);
    border: 1px solid var(--color-border-subtle);
  }
  .logout-btn {
    color: var(--color-accent-danger);
    font-size: var(--size-sm);
    font-weight: var(--weight-medium);
    cursor: pointer;
    transition: color var(--motion-duration-fast) var(--motion-easing-standard);
  }
  .logout-btn:hover {
    color: var(--color-accent-danger);
    text-decoration: underline;
  }
  .divider {
    width: 1px;
    height: 24px;
    background: var(--color-border-subtle);
    margin: 0 var(--space-xs);
  }
</style>

// apps/build-monitor/react/src/components/Header.tsx
// TASK-095: Header (React).
//
// Svelte src/components/Header.svelte 와 1:1 정합. userId admin allow-list
// auto-enable (TASK-076 + 077 + 048) + admin 단일 진입점 + New Build +
// API Console + OpenAPI + Docs + ThemeToggle 통합.
//
// react-router-dom v7 의 <Link> 사용. Zustand adminAllowListStore 로
// admin list 캐시 + add/remove + contains(userId). React `useUserId` hook
// (TASK-089 follow-up) 의 setUserId 로 logout.
//
// a11y: nav 의 의미적 `<nav>` element + role 의미는 link element 자체로
// 충분히 전달. 구분선 `<div class="divider">` 는 aria-hidden 으로 처리.

import { useEffect, type CSSProperties, type ReactElement } from "react";
import { Link, useNavigate } from "react-router-dom";

import { setUserId, useUserId } from "@/lib/useUserId";
import { useAdminAllowListStore } from "@/lib/stores/adminAllowListStore";
import { ThemeToggle } from "@/components/ThemeToggle";

import "./Header.css";

export function Header(): ReactElement {
  const [userId] = useUserId();
  const admins = useAdminAllowListStore((s) => s.admins);
  const refreshAllowList = useAdminAllowListStore((s) => s.refresh);
  const navigate = useNavigate();

  // userId 가 admin allow-list 에 속하면 admin 으로 auto-enable.
  // userId 가 없거나 allow-list 가 비어있으면 false.
  const autoAdminEnabled =
    !!userId && admins.length > 0 && admins.includes(userId);
  const effectiveAdminId = autoAdminEnabled ? userId : null;

  useEffect(() => {
    // 부팅 시 userId 가 있으면 admin allow-list 를 prefetch.
    if (userId && admins.length === 0) {
      refreshAllowList(userId).catch(() => {
        // intentional: stale cache; admin menu stays hidden until next
        // successful refresh (e.g. next page navigation trigger).
      });
    }
    // refreshAllowList reference 가 안정적이라 userId / admins 만 의존.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId]);

  function logout(): void {
    // userId 가 admin allow-list 에 있었더라도, logout 하면 더 이상
    // admin 메뉴는 노출되지 않는다 — userId null 이 되면 autoAdminEnabled
    // 도 false 가 되므로 admin 메뉴가 자연스럽게 사라진다.
    setUserId(null);
    navigate("/");
  }

  return (
    <header className="hdr" data-testid="app-header">
      <div className="hdr-inner">
        <Link to="/" className="brand" data-testid="hdr-brand">
          <div className="logo-wrapper">
            <span className="logo" aria-hidden="true">
              ⬢
            </span>
          </div>
          <span className="title">Build Monitor</span>
        </Link>
        <nav className="hdr-nav">
          {userId ? (
            <>
              <span className="user-id mono" data-testid="hdr-user-id">
                @{userId}
              </span>
              <Link
                to="/builds"
                className="hdr-link"
                data-testid="hdr-builds"
              >
                Builds
              </Link>
              {/* TASK-079 (skill 측 build request UI): 일반 인증 사용자
                   (admin 여부 무관) 가 POST /builds payload 를 직접 작성해
                   lifecycle 을 시험할 수 있는 진입점. */}
              <Link
                to="/build-request"
                className="hdr-link"
                data-testid="hdr-new-build"
              >
                New Build
              </Link>
              <button
                type="button"
                className="logout-btn"
                onClick={logout}
                data-testid="hdr-logout"
              >
                Logout
              </button>
            </>
          ) : null}
          {effectiveAdminId ? (
            <>
              <div className="divider" aria-hidden="true" />
              <span
                className="admin-id mono"
                title="Admin session active"
                data-testid="hdr-admin-id"
              >
                🛡 @{effectiveAdminId}
              </span>
              {/* TASK-077: admin 진입점은 단일 링크. 각 admin 섹션
                   (Builds / Users / Admins / Runners) 사이의 이동은
                   페이지 상단 <AdminTabs /> 가 담당. */}
              <Link
                to="/admin/builds"
                className="hdr-link"
                data-testid="hdr-admin"
              >
                Admin
              </Link>
            </>
          ) : null}
          <div className="divider" aria-hidden="true" />
          <Link
            to="/api-console"
            className="hdr-link"
            data-testid="hdr-api-console"
          >
            API Console
          </Link>
          <a
            href="/openapi.json"
            target="_blank"
            rel="noopener"
            className="hdr-link"
            data-testid="hdr-openapi"
          >
            OpenAPI
          </a>
          <a
            href="/docs/"
            target="_blank"
            rel="noopener"
            className="hdr-link"
            data-testid="hdr-docs"
          >
            Docs
          </a>
          <div className="divider" aria-hidden="true" />
          <ThemeToggle />
        </nav>
      </div>
    </header>
  );
}

// CSSProperties type re-export 방지 (unused).
export type HeaderCSSProperties = CSSProperties;
