// apps/build-monitor/src/components/LogStream.svelte
<script lang="ts">
  /**
   * LogStream — DESIGN.md §3 Components.
   * Monospace, since cursor 기반 증분 fetch (PR #6 1차 골격은 sample data).
   * auto-scroll 토글 후속.
   */
  type LogEntry = { id?: string; buildId?: string; phase: string; message: string; createdAt: string };

  let { entries }: { entries: LogEntry[] } = $props();
  let wrap = $state(false);
</script>

<div class="wrap">
  <div class="toolbar">
    <label>
      <input type="checkbox" bind:checked={wrap} /> wrap
    </label>
  </div>
  <pre class="stream" class:wrap>{#each entries as e (e.createdAt + e.message)}<span class="entry"><span class="at mono">{e.createdAt.slice(11, 19)}</span> <span class="phase mono">[{e.phase}]</span> {e.message}{'\n'}</span>{/each}</pre>
</div>

<style>
  .wrap { 
    display: flex; 
    flex-direction: column; 
    gap: var(--space-md); 
  }
  .toolbar { 
    display: flex; 
    gap: var(--space-md); 
    color: var(--color-text-secondary); 
    font-size: var(--size-sm); 
    align-items: center;
    background: var(--color-bg-canvas);
    padding: var(--space-xs) var(--space-md);
    border-radius: var(--radius-sm);
    border: 1px solid var(--color-border-subtle);
    width: fit-content;
  }
  .toolbar input {
    accent-color: var(--color-accent-primary);
  }
  .stream {
    background: var(--code-bg);
    border: 1px solid var(--code-border);
    border-radius: var(--radius-md);
    padding: var(--space-lg);
    font-family: var(--font-mono);
    font-size: var(--size-sm);
    line-height: var(--line-relaxed);
    color: var(--code-fg);
    margin: 0;
    max-height: 480px;
    overflow: auto;
    white-space: pre;
    box-shadow: var(--code-inset-shadow);
  }
  .stream.wrap {
    white-space: pre-wrap;
    word-break: break-word;
  }
  .at { color: var(--code-muted); }
  .phase { color: var(--code-phase); font-weight: var(--weight-semibold); }
</style>

// apps/build-monitor/react/src/components/LogStream.tsx
// TASK-091: LogStream (React).
//
// Svelte src/components/LogStream.svelte 와 1:1 정합. wrap 토글 +
// auto-scroll 토글 후속. 디자인 토큰 — --code-bg / --code-border /
// --code-fg / --code-muted / --code-phase / --code-inset-shadow.
//
// at 슬라이스 (`e.createdAt.slice(11, 19)`) 는 ISO 8601 의 HH:MM:SS
// 부분 — 운영자가 log stream 을 빠르게 스캔.

import { useState } from "react";
import type { CSSProperties, ReactElement } from "react";

import type { BuildLogEntry } from "@/lib/api";

function LogEntrySpan({ entry }: { entry: BuildLogEntry }): ReactElement {
  const atStyle: CSSProperties = {
    color: "var(--code-muted)",
    fontFamily: "var(--font-mono)"
  };
  const phaseStyle: CSSProperties = {
    color: "var(--code-phase)",
    fontWeight: "var(--weight-semibold)",
    fontFamily: "var(--font-mono)"
  };
  return (
    <span data-testid="log-entry">
      <span style={atStyle}>{entry.createdAt.slice(11, 19)}</span>{" "}
      <span style={phaseStyle}>[{entry.phase}]</span>{" "}
      {entry.message}
      {"\n"}
    </span>
  );
}

export function LogStream({
  entries
}: {
  entries: BuildLogEntry[];
}): ReactElement {
  const [wrap, setWrap] = useState(false);

  const wrapStyle: CSSProperties = {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-md)"
  };

  const toolbarStyle: CSSProperties = {
    display: "flex",
    gap: "var(--space-md)",
    color: "var(--code-muted)",
    fontSize: "var(--size-sm)",
    alignItems: "center",
    padding: "var(--space-xs) var(--space-md)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-sm)",
    background: "var(--color-bg-canvas)",
    width: "fit-content"
  };

  const preBaseStyle: CSSProperties = {
    background: "var(--code-bg)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-lg)",
    fontFamily: "var(--font-mono)",
    fontSize: "var(--size-sm)",
    lineHeight: "var(--line-relaxed)",
    color: "var(--code-fg)",
    margin: 0,
    maxHeight: "480px",
    overflow: "auto",
    whiteSpace: "pre",
    boxShadow: "var(--code-inset-shadow)"
  };

  const preWrapStyle: CSSProperties = {
    ...preBaseStyle,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word"
  };

  return (
    <div data-testid="log-stream" style={wrapStyle}>
      <div style={toolbarStyle}>
        <label style={{ display: "flex", gap: "var(--space-sm)" }}>
          <input
            type="checkbox"
            data-testid="log-stream-wrap"
            checked={wrap}
            onChange={(e) => setWrap(e.target.checked)}
          />
          wrap
        </label>
      </div>
      <pre
        data-testid="log-stream-pre"
        style={wrap ? preWrapStyle : preBaseStyle}
      >
        {entries.map((entry, idx) => {
          const key = `${entry.id}-${entry.createdAt}-${idx}`;
          return <LogEntrySpan key={key} entry={entry} />;
        })}
      </pre>
    </div>
  );
}
