// apps/build-monitor/src/components/ThemeToggle.svelte
<script lang="ts">
  import { onMount } from "svelte";

  let isLight = $state(false);

  onMount(() => {
    // Check local storage or system preference
    const stored = localStorage.getItem("theme");
    if (stored === "light") {
      isLight = true;
    } else if (!stored && window.matchMedia("(prefers-color-scheme: light)").matches) {
      isLight = true;
    }
    applyTheme(isLight);
    // onMount 가 applyTheme 을 호출하지만, 첫 마운트 시점에 isLight 가
    // 이미 true/false 로 결정된 후 라 style.colorScheme 도 같이 set.
    // (applyTheme 안에서 set 하지만, isLight 가 false 인 경우 setAttribute
    // 가 호출되지 않을 가능성 — onMount 끝에서 명시 보강.)
    if (!isLight) {
      document.documentElement.style.colorScheme = "dark";
    }
  });

  function toggle() {
    isLight = !isLight;
    applyTheme(isLight);
  }

  function applyTheme(light: boolean) {
    if (light) {
      document.documentElement.setAttribute("data-theme", "light");
      // TASK-046: native form 컨트롤 (input, select, scrollbar) 도
      // light 모드에 맞춤. theme.css 의 :root[data-theme="light"] selector
      // 가 css-side 에서 set 하지만, 일부 환경 (jsdom) 에서 computed
      // style 검증이 필요할 때를 위해 js-side 에서도 명시.
      document.documentElement.style.colorScheme = "light";
      localStorage.setItem("theme", "light");
    } else {
      document.documentElement.removeAttribute("data-theme");
      document.documentElement.style.colorScheme = "dark";
      localStorage.setItem("theme", "dark");
    }
  }
</script>

<button class="theme-btn" onclick={toggle} aria-label="Toggle theme">
  {#if isLight}
    <!-- Moon icon for switching to dark -->
    <svg viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
    </svg>
  {:else}
    <!-- Sun icon for switching to light -->
    <svg viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="12" cy="12" r="5"></circle>
      <line x1="12" y1="1" x2="12" y2="3"></line>
      <line x1="12" y1="21" x2="12" y2="23"></line>
      <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
      <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
      <line x1="1" y1="12" x2="3" y2="12"></line>
      <line x1="21" y1="12" x2="23" y2="12"></line>
      <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
      <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
    </svg>
  {/if}
</button>

<style>
  .theme-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 36px;
    height: 36px;
    border-radius: var(--radius-pill);
    color: var(--color-text-secondary);
    background: transparent;
    transition: all var(--motion-duration-fast) var(--motion-easing-standard);
  }
  .theme-btn:hover {
    background: var(--color-bg-surface-elevated);
    color: var(--color-text-primary);
    transform: scale(1.05);
  }
</style>

// apps/build-monitor/react/src/components/ThemeToggle.tsx
// TASK-095: ThemeToggle (React).
//
// Svelte src/components/ThemeToggle.svelte 와 1:1 정합. light/dark 토글
// + localStorage 영속화 + system preference fallback.
//
// a11y: aria-label "Toggle theme" + role="button" (button element).
//
// 디자인 토큰: --color-text-secondary / --color-bg-surface-elevated /
// --color-text-primary / --radius-pill / --motion-duration-fast /
// --motion-easing-standard. globals.css cascade 와 정합.

import { useEffect, useState, type ReactElement } from "react";

const STORAGE_KEY = "theme";

function readInitialTheme(): boolean {
  if (typeof window === "undefined") {
    return false;
  }
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (stored === "light") {
    return true;
  }
  if (stored === "dark") {
    return false;
  }
  // system preference fallback — prefers-color-scheme: light 일 때 light.
  // jsdom 에는 matchMedia 가 없어 try/catch 로 fallback.
  try {
    return window.matchMedia("(prefers-color-scheme: light)").matches;
  } catch {
    return false;
  }
}

function applyTheme(light: boolean): void {
  if (typeof document === "undefined") {
    return;
  }
  if (light) {
    document.documentElement.setAttribute("data-theme", "light");
    document.documentElement.style.colorScheme = "light";
    window.localStorage.setItem(STORAGE_KEY, "light");
  } else {
    document.documentElement.removeAttribute("data-theme");
    document.documentElement.style.colorScheme = "dark";
    window.localStorage.setItem(STORAGE_KEY, "dark");
  }
}

export function ThemeToggle(): ReactElement {
  // 첫 마운트 시점의 theme 결정은 useEffect 안에서 (DOM 접근 필요).
  // useState 의 initial value 는 SSR-safe 한 default (dark) 로 두고,
  // mount 후 readInitialTheme() 로 동기화. 단, 첫 paint 시점에는
  // light 가 결정될 가능성도 있어 SSR / hydration 시점 mismatch 가 발생할
  // 수 있다 — 본 React SPA 는 client-side only 라 hydration 단계 없으므로
  // 안전.
  const [isLight, setIsLight] = useState(false);

  useEffect(() => {
    const initial = readInitialTheme();
    setIsLight(initial);
    applyTheme(initial);
    // 첫 마운트 시 isLight 가 false 인 경우 setAttribute 가 호출되지
    // 않을 가능성 — 명시 보강.
    if (!initial) {
      document.documentElement.style.colorScheme = "dark";
    }
  }, []);

  function toggle(): void {
    const next = !isLight;
    setIsLight(next);
    applyTheme(next);
  }

  const buttonStyle = {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "36px",
    height: "36px",
    borderRadius: "var(--radius-pill)",
    color: "var(--color-text-secondary)",
    background: "transparent",
    border: "1px solid transparent",
    cursor: "pointer",
    transition:
      "all var(--motion-duration-fast) var(--motion-easing-standard)"
  };

  return (
    <button
      type="button"
      data-testid="theme-toggle"
      aria-label="Toggle theme"
      style={buttonStyle}
      onClick={toggle}
      onMouseEnter={(e) => {
        e.currentTarget.style.background = "var(--color-bg-surface-elevated)";
        e.currentTarget.style.color = "var(--color-text-primary)";
        e.currentTarget.style.transform = "scale(1.05)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.background = "transparent";
        e.currentTarget.style.color = "var(--color-text-secondary)";
        e.currentTarget.style.transform = "scale(1)";
      }}
    >
      {isLight ? (
        // Moon icon — switching to dark
        <svg
          viewBox="0 0 24 24"
          width="20"
          height="20"
          stroke="currentColor"
          strokeWidth="2"
          fill="none"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
        </svg>
      ) : (
        // Sun icon — switching to light
        <svg
          viewBox="0 0 24 24"
          width="20"
          height="20"
          stroke="currentColor"
          strokeWidth="2"
          fill="none"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="5" />
          <line x1="12" y1="1" x2="12" y2="3" />
          <line x1="12" y1="21" x2="12" y2="23" />
          <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
          <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
          <line x1="1" y1="12" x2="3" y2="12" />
          <line x1="21" y1="12" x2="23" y2="12" />
          <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
          <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
        </svg>
      )}
    </button>
  );
}
