// apps/build-monitor/src/routes/BuildsList.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { push } from "svelte-spa-router";
  import BuildRow from "../components/BuildRow.svelte";
  import type { BuildSummary } from "../lib/api";
  import { listBuilds } from "../lib/api";

  let builds = $state<BuildSummary[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let userId = $state<string | null>(null);

  onMount(async () => {
    userId = localStorage.getItem("userId");
    if (!userId) {
      push("/");
      return;
    }
    
    try {
      const result = await listBuilds();
      builds = result.builds;
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  });

  // status filter chips
  let filter = $state<"ALL" | "BUILDING" | "COMPLETED" | "FAILED">("ALL");
  
  // filter by userId (matching projectId) and then by status
  let visible = $derived(
    builds
      .filter((b) => !userId || b.projectId.includes(userId))
      .filter((b) => filter === "ALL" || b.status === filter)
  );
</script>

<section class="list-page">
  <header class="page-head">
    <h1>Builds</h1>
    <div class="chips" role="group" aria-label="Status filter">
      {#each ["ALL", "BUILDING", "COMPLETED", "FAILED"] as f (f)}
        <button
          type="button"
          class="chip"
          class:active={filter === f}
          aria-pressed={filter === f}
          onclick={() => (filter = f as typeof filter)}
        >{f}</button>
      {/each}
    </div>
  </header>

  {#if loading}
    <p class="muted">Loading…</p>
  {:else if error}
    <p class="err" role="alert">{error}</p>
  {:else if visible.length === 0}
    <p class="muted">No builds.</p>
  {:else}
    <table>
      <thead>
        <tr>
          <th>Status</th>
          <th>Build</th>
          <th>Project</th>
          <th>Repository</th>
          <th class="r">Updated</th>
        </tr>
      </thead>
      <tbody>
        {#each visible as b (b.buildId)}
          <BuildRow build={b} />
        {/each}
      </tbody>
    </table>
  {/if}
</section>

<style>
  .list-page { 
    display: flex; 
    flex-direction: column; 
    gap: var(--space-xxl); 
    animation: fadeIn var(--motion-duration-slow) var(--motion-easing-standard);
  }
  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
  }
  .page-head { 
    display: flex; 
    align-items: center; 
    justify-content: space-between; 
  }
  h1 { 
    margin: 0; 
    font-size: var(--size-xxl); 
    font-weight: var(--weight-semibold); 
    letter-spacing: -0.02em;
    background: linear-gradient(90deg, var(--color-text-primary), var(--color-text-muted));
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
  }
  .chips { 
    display: inline-flex; 
    gap: var(--space-sm); 
    background: var(--color-bg-surface);
    padding: var(--space-xs);
    border-radius: var(--radius-pill);
    border: 1px solid var(--color-border-subtle);
    box-shadow: var(--shadow-card);
  }
  .chip {
    padding: var(--space-sm) var(--space-lg);
    border-radius: var(--radius-pill);
    background: transparent;
    color: var(--color-text-secondary);
    font-size: var(--size-sm);
    font-weight: var(--weight-medium);
    border: 1px solid transparent;
    transition: all var(--motion-duration-fast) var(--motion-easing-standard);
  }
  .chip:hover {
    color: var(--color-text-primary);
  }
  .chip.active { 
    background: var(--color-accent-primary); 
    color: white; 
    box-shadow: 0 4px 12px rgba(99, 102, 241, 0.4);
  }
  
  table { 
    width: 100%; 
    border-collapse: separate; 
    border-spacing: 0;
    background: var(--color-bg-surface); 
    border: 1px solid var(--color-border-subtle); 
    border-radius: var(--radius-lg); 
    box-shadow: var(--shadow-card);
    overflow: hidden; 
  }
  thead th { 
    text-align: left; 
    padding: var(--space-md) var(--space-lg); 
    background: var(--color-bg-surface-elevated); 
    color: var(--color-text-muted); 
    font-size: var(--size-xs); 
    font-weight: var(--weight-semibold); 
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border-bottom: 1px solid var(--color-border-subtle); 
  }
  thead th.r { text-align: right; }
  .muted { color: var(--color-text-muted); }
  .err { color: var(--color-accent-danger); }
</style>

// apps/build-monitor/react/src/routes/BuildsList.tsx
// TASK-090: BuildsList (React).
//
// Svelte src/routes/BuildsList.svelte 와 1:1 정합 — localStorage.userId
// 확인 → /builds API 호출 → builds set → status chip filter → BuildRow.
// 인증 정보 없으면 `/` 로 redirect (Login 페이지 진입 후 다시 /builds).
//
// FilterChips Svelte 컴포넌트는 React 변환 시 같은 디자인 토큰 + 인터랙션
// 패턴을 inline button 으로 단순 구현 — 본 task 범위는 페이지 자체의
// 1:1 마이그레이션이며 chip 디자인 시스템의 React 컴포넌트화는
// TASK-092 (lib layer 마이그레이션) 이후 검토.

import { useEffect, useMemo, useState, type ReactElement } from "react";
import { useNavigate } from "react-router-dom";

import { BuildRow } from "@/components/BuildRow";
import { listBuilds, type BuildSummary } from "@/lib/api";
import { matchesChip, type StatusFilter } from "@/lib/chipFilter";
import { useUserId } from "@/lib/useUserId";
import "./BuildsList.css";

export function BuildsList(): ReactElement {
  const [userId] = useUserId();
  const navigate = useNavigate();
  const [builds, setBuilds] = useState<BuildSummary[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<StatusFilter>("ALL");

  useEffect(() => {
    if (userId === null) {
      setLoading(false);
      navigate("/", { replace: true });
      return;
    }

    let cancelled = false;
    (async () => {
      try {
        const result = await listBuilds({ requestedBy: userId });
        if (!cancelled) {
          setBuilds(result.builds);
        }
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : String(e));
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [userId, navigate]);

  const visible = useMemo(() => {
    if (filter === "ALL") return builds;
    return builds.filter((b) => matchesChip(b, filter));
  }, [builds, filter]);

  const filterChips: StatusFilter[] = [
    "ALL",
    "BUILDING",
    "COMPLETED",
    "FAILED"
  ];

  return (
    <section className="list-page">
      <header className="page-head">
        <h1>Builds</h1>
        <div className="chips" role="group" aria-label="Status filter">
          {filterChips.map((chip) => (
            <button
              key={chip}
              type="button"
              className={`chip${filter === chip ? " chip--active" : ""}`}
              onClick={() => {
                setFilter(chip);
              }}
              aria-pressed={filter === chip}
            >
              {chip}
            </button>
          ))}
        </div>
      </header>

      {loading ? (
        <p className="muted">Loading…</p>
      ) : error !== null ? (
        <p className="err" role="alert">{error}</p>
      ) : visible.length === 0 ? (
        <p className="muted">No builds.</p>
      ) : (
        <table className="builds-table">
          <thead>
            <tr>
              <th>Status</th>
              <th>Build</th>
              <th>App</th>
              <th className="r">Updated</th>
            </tr>
          </thead>
          <tbody>
            {visible.map((b) => (
              <BuildRow key={b.buildId} build={b} />
            ))}
          </tbody>
        </table>
      )}
    </section>
  );
}
